### PR TITLE
DO NOT MERGE: CI Testing #897

### PR DESCRIPTION
**Pull request by mjcarroll**
#897

### CODE REVIEW

**Comment by mjcarroll** [comment]
@osrf-jenkins retest this please

**Comment by peci1** [comment]
The build got stuck somehow... :(

**Comment by mjcarroll** [comment]
Here is the rebuild: https://build.osrfoundation.org/job/ign_rendering-pr-win/3326

**Comment by mjcarroll** [comment]
Looks like it still didn't find OGRE2 from vcpkg.  I have to get my Windows laptop out for other things today, I will check this on there.

**Pull request closed without merging**
