### PR TITLE
Add LensFlare to ogre1

### LINKED ISSUE #730: Port LensFlare from gazebo-classic
## Desired behavior

The lens flare behavior embodied in the [gazebo::rendering::LensFlare](https://github.com/osrf/gazebo/blob/gazebo11/gazebo/rendering/LensFlare.hh) class should be supported in gz-rendering by the `ogre` and `ogre2` components. The following animation from [bitbucket pull request 2915](https://osrf-migration.github.io/gazebo-gh-pages/#!/osrf/gazebo/pull-requests/2915/page/1) illustrates the effect.

lens flare demonstration

### PR DESCRIPTION
**Pull request by darksylinc**
# 🎉 New feature

Closes #730

## Summary

Previous PR #752 added LensFlarePass to ogre2.
This PR adds LensFlarePass to ogre1.

This includes LensFlarePass support for ogre1's WideAngleCamera.
WideAngleCamera had to be modified a little to support RenderPass at all.

In theory the gaussian filter pass should also work with WideAngleCamera but I did not test it.

It also implements OgreWideAngleCamera::Copy so that integration tests can function (Ogre2WideAngleCamera::Copy had already been implemented).

OgreRayQuery also had to be modified to support OgreWideAngleCamera; since LensFlares need ray queries for occlusion support.

Additionally I add `RemoveAllRenderPasses` since I noticed a lot of RenderPasses didn't get to properly deinitialize. Though it didn't seem like much harm was being done because currently all RenderPasses are very simple.

**IMPORTANT:** LensFlare occlusion in ogre1 is ridiculously slow on my HW. It may be due to a known OpenGL driver bug for my GPU (downloading vertex data from GPU back to CPU in Radeon RX 6800 XT), or it may be slow for everyone.

Frankly I didn't bother profiling too much: For offline simulations I suppose it's good enough; if this is a problem one can either use ogre2, or use ogre1 and temporarily disable occlusion (call `SetOcclusionSteps` to 0) while working in realtime with it.

If you need that fixed we can open a new ticket and I'll take a deeper look.

## Test it

See PR #752

## Checklist
- [x] Signed all commits for DCO
- [x] Added tests
- [ ] Added example and/or tutorial
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [ ] Consider updating Python bindings (if the library has them)
- [x] `codecheck` passed (See [contributing](https://gazebosim.org/docs/all/contributing#contributing-code))
- [x] All tests passed (See [test coverage](https://gazebosim.org/docs/all/contributing#test-coverage))
- [ ] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Agazebosim+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` messages.

### CODE REVIEW

**Comment by darksylinc** [comment]
Codecov says `RemoveAllRenderPasses` is never getting called, which is a huge red flag.

I'm converting this PR to a draft until that fixes.

Although from preliminary analysis it looks like `Ogre2RenderTexture::Destroy` (already fixed) and `OgreRenderTexture::Destroy` (fixing, but right now crashing) are never getting called which is a bigger issue probably affecting older versions as well.

**Comment by darksylinc** [comment]
Oooof. That last red flag [opened Pandora's Box](https://github.com/gazebosim/gz-rendering/pull/775/commits/d2abccd2e06fd7e803a90ef0cb4cff8f5d4a3b86).

I will have to backport that commit back to Fortress (AFAICT it should be backported to Citadel as well but I'm not covering that madness).

**Comment by darksylinc** [comment]
OK after a few tries, got it sorted out.

 - macOS is complaining about VisualAt. Unrelated.


 - Windows is complaining about a link error. It makes no sense!

OgreLensFlarePass.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: __cdecl gz::rendering::v8::LensFlarePass::LensFlarePass(void)" (__imp_??0LensFlarePass@v8@rendering@gz@@QEAA@XZ) [C:\Jenkins\workspace\ign_rendering-pr-win\ws\build\gz-rendering8\ogre\src\gz-rendering8-ogre.vcxproj]

OgreLensFlarePass.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: virtual __cdecl gz::rendering::v8::LensFlarePass::~LensFlarePass(void)" (__imp_??1LensFlarePass@v8@rendering@gz@@UEAA@XZ) [C:\Jenkins\workspace\ign_rendering-pr-win\ws\build\gz-rendering8\ogre\src\gz-rendering8-ogre.vcxproj]

```
OgreLensFlarePass.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: class gz::rendering::v8::LensFlarePass & __cdecl gz::rendering::v8::LensFlarePass::operator=(class gz::rendering::v8::LensFlarePass const &)" (__imp_??4LensFlarePass@v8@rendering@gz@@QEAAAEAV0123@AEBV0123@@Z) [C:\Jenkins\workspace\ign_rendering-pr-win\ws\build\gz-rendering8\ogre\src\gz-rendering8-ogre.vcxproj]
```

`LensFlarePass` doesn't (apparently? Maybe a rogue macro I missed?) have explicitly defined constructors, destructors nor copy operators. So this could indicate either a caching problem or linkage error (e.g. `__declspec(dllimport)` vs `__declspec(dllexport)`(

What baffles me is that this error doesn't happen with ogre2, despite seemingly being identical.

**Comment by iche033** [comment]
For the `unresolved external symbol` issues, we've seen similar errors before on windows. We solved them by explicitly declaring the constructor/destructor in the .hh file and then defining the functions in a .cc src files, e.g.  [GaussianNoisePass.cc](https://github.com/gazebosim/gz-rendering/blob/gz-rendering7/src/GaussianNoisePass.cc). See if that makes a difference.

**Comment by darksylinc** [comment]
**YES!!!**

Rebased the project.

All checks passed.

Windows MSVC link error fixed with your workaround (thanks @iche033). This is clearly a linker bug I think.

It's ready to be merged.

**Comment by iche033** [comment]
Nice works well for cameras:

Screenshot from 2022-12-14 15-55-47

I tested with wide angle camera and noticed the issue with 'edges' between env cameras.

<details><summary>wide_angle_camera example patch</summary>

```diff
diff --git a/examples/wide_angle_camera/Main.cc b/examples/wide_angle_camera/Main.cc
index 02da3612..399927c8 100644
--- a/examples/wide_angle_camera/Main.cc
+++ b/examples/wide_angle_camera/Main.cc
@@ -51,7 +51,7 @@ void buildScene(ScenePtr _scene)
 
   // create directional light
   DirectionalLightPtr light0 = _scene->CreateDirectionalLight();
-  light0->SetDirection(0.5, 0.5, -1);
+  light0->SetDirection(-1, 0.3, -0.3);
   light0->SetDiffuseColor(0.8, 0.8, 0.8);
   light0->SetSpecularColor(0.5, 0.5, 0.5);
   root->AddChild(light0);
@@ -134,6 +134,19 @@ void buildScene(ScenePtr _scene)
   camera->SetAspectRatio(1.333);
   root->AddChild(camera);
 //! [create wide angle camera]
+
+   RenderPassSystemPtr rpSystem = _scene->Engine()->RenderPassSystem();
+   if (rpSystem)
+   {
+     auto light = _scene->LightByIndex(0u);
+     RenderPassPtr p = rpSystem->Create<LensFlarePass>();
+     LensFlarePassPtr lensFlarePass =
+       std::dynamic_pointer_cast<LensFlarePass>(p);
+     lensFlarePass->Init(_scene);
+     lensFlarePass->SetEnabled(true);
+     lensFlarePass->SetLight(light);
+     camera->AddRenderPass(lensFlarePass);
+   }
```

</details>

Screenshot from 2022-12-14 16-12-26

I think that's because the lens flare render pass is applied to all env cameras first before being stitched together?

In gazebo-classic, the lens flare effect is done on the final stitched image with the caveat that the lens flares are not distorted by the wide angle view:

Screenshot from 2022-12-14 16-24-41

If we have to pick one limitation to go with, we should probably go with the original behavior with no edges. The edges  may cause issues with image processing algorithms. Sorry didn't catch this earlier for ogre2 implementation. Can you make this change?

**Comment by darksylinc** [comment]
I've updated the PR with further changes.

It fixes various bugs I found with Ogre2 implementation.

And more importantly it adds `RenderPass::SetWideAngleCameraAfterStitching` (defaults to true for LensFlare, false for GaussianNoise) so that users can control whether Noise is done with or without distortion; while lens flare is done without distortion so that it doesn't have the problems you mention.

This took WAY longer than I thought. But it's done.

Unfortunately now coverage has been reduced since new code was added and integration tests are not covering all possible paths. However the existing integration test is passing AND was pivotal in getting this new feature working well.

Since my contract is ending soon, I'd like to move on the pending tasks (Metal compiler error in the Qt / GUI PR, and rebasing VCT)

**Comment by iche033** [comment]
lens flares in wide angle camera look good to me!

Screenshot from 2022-12-19 14-52-25

**Review by iche033 — APPROVED** [review]

**Pull request merged**
