### PR TITLE
Enable ogre2 heightmap test

### PR DESCRIPTION
**Pull request by iche033**
Signed-off-by: Ian Chen <ichen@osrfoundation.org>

# 🦟 Bug fix

## Summary

Run `Heightmap_test` with `ogre2` now that it is supported

This unfortunately reduces the overall test coverage % because various ogre1.x code is not run any more.

## Checklist
- [x] Signed all commits for DCO
- [x] Added tests
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [ ] Consider updating Python bindings (if the library has them)
- [ ] `codecheck` passed (See [contributing](https://ignitionrobotics.org/docs/all/contributing#contributing-code))
- [ ] All tests passed (See [test coverage](https://ignitionrobotics.org/docs/all/contributing#test-coverage))
- [ ] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Aignitionrobotics+repo%3Aosrf%2Fsdformat+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` messages.

### CODE REVIEW

**Comment by chapulina** [comment]
> This unfortunately reduces the overall test coverage % because various ogre1.x code is not run any more.

If we're not planning to test both engines, then we should exclude the other one from test coverage. I think we should test all engines that we officially support though. What do you think?

**Comment by iche033** [comment]
> I think we should test all engines that we officially support though.

The problem we ran into before was that we were not able to run ogre and ogre2 tests in the same process, i.e. one after another since the plugins can't be loaded at the same time. We could look into generating tests for each render engine so that they are run in separate processes, e.g. UNIT_ogre_Scene_TEST and UNIT_ogre2_Scene_TEST.

**Comment by chapulina** [comment]
How about we ticket an issue for that, and for now we exclude Ogre1 and Optix from the coverage reports?

**Comment by iche033** [comment]
> How about we ticket an issue for that, and for now we exclude Ogre1 and Optix from the coverage reports?

yep ticketed #683  and created https://github.com/gazebosim/gz-rendering/pull/684 to ignore certain folders in text coverage

**Review by chapulina — APPROVED** [review]

**Pull request merged**
