### PR TITLE
Include the CGL header on macOS

### PR DESCRIPTION
**Pull request by mjcarroll**
Fix break from #897

### CODE REVIEW

**Comment by iche033** [comment]
looks good, will wait for CI

**Comment by scpeters** [comment]
[Build Status](https://build.osrfoundation.org/job/ignition_rendering-ci-pr_any-homebrew-amd64/3218/) https://build.osrfoundation.org/job/ignition_rendering-ci-pr_any-homebrew-amd64/3218/

**Review by scpeters — APPROVED** [review]

**Comment by scpeters** [comment]
thanks for the quick fix!

**Review by iche033 — APPROVED** [review]

**Comment by scpeters** [comment]
CI failure seems like a problem with the machine?

[Build Status](https://build.osrfoundation.org/job/gz_rendering-ci-pr_any-jammy-amd64/49/) https://build.osrfoundation.org/job/gz_rendering-ci-pr_any-jammy-amd64/49/

~~~
27: [ RUN      ] HeightmapTest.Heightmap
27: X Error of failed request:  GLXBadDrawable
27:   Major opcode of failed request:  151 (GLX)
27:   Minor opcode of failed request:  5 (X_GLXMakeCurrent)
27:   Serial number of failed request:  58
27:   Current serial number in output stream:  58
27: [1;36m[Dbg] [CommonRenderingTest.hh:44] [0m[1;36mRead GZ_ENGINE_TO_TEST=[0m[1;36mogre[0m[1;36m[0m
27: [1;36m[Dbg] [CommonRenderingTest.hh:47] [0m[1;36mRead GZ_ENGINE_BACKEND=[0m[1;36mgl3plus[0m[1;36m[0m
27: [1;32m[Msg] [0m[1;32mLoading plugin [[0m[1;32mgz-rendering-ogre[0m[1;32m][0m[1;32m[0m
 27/245 Test  #27: INTEGRATION_heightmap_ogre_gl3plus ....................***Failed    0.24 sec
~~~

**Comment by peci1** [comment]
Or it could actually be a wrongly initialized GL context...

**Comment by azeey** [comment]
I reran the Jammy job and it passed (https://build.osrfoundation.org/job/gz_rendering-ci-pr_any-jammy-amd64/51/), so I'd say this is okay to merge.

**Comment by mjcarroll** [comment]
Yeah, this should not have altered any jammy specific code paths, so maybe just a flake?

**Pull request merged**
