### PR TITLE
ign -> gz CMake, Python, Partial Source, and File Migrations : gz-rendering

### PR DESCRIPTION
**Pull request by methylDragon**
See: https://github.com/gazebo-tooling/release-tools/issues/765

### CODE REVIEW

**Comment by methylDragon** [comment]
@osrf-jenkins run tests please!

**Comment by methylDragon** [comment]
@osrf-jenkins run tests please!

**Comment by methylDragon** [comment]
@osrf-jenkins run tests please!

**Comment by methylDragon** [comment]
@osrf-jenkins run tests please!

**Review by chapulina — APPROVED** [review]

**Pull request merged**
