### PR TITLE
Camera ShaderSelection: avoid seg-fault

### PR DESCRIPTION
**Pull request by scpeters**
# 🦟 Bug fix

Improves error reporting for failing test

## Summary

A test was re-enabled for macOS in https://github.com/gazebosim/gz-rendering/pull/703, but it seems to still fail on certain machines (see comments below https://github.com/gazebosim/gz-rendering/pull/703#issuecomment-1245856857).

The test currently seg-faults after an `EXPECT_*` statement is used to check for a nullptr and the pointer is later dereferenced. Wrap the subsequent check in an if statement to allow the rest of the test to continue instead of using `ASSERT_*`. This doesn't fix the underlying issue but it should allow the test to proceed a bit farther and provide more useful failure reporting.

## Checklist
- [ ] Signed all commits for DCO
- [ ] Added tests
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [ ] Consider updating Python bindings (if the library has them)
- [ ] `codecheck` passed (See [contributing](https://gazebosim.org/docs/all/contributing#contributing-code))
- [ ] All tests passed (See [test coverage](https://gazebosim.org/docs/all/contributing#test-coverage))
- [ ] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Agazebosim+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` messages.

### CODE REVIEW

**Comment by scpeters** [comment]
test failed again on glados:

* https://build.osrfoundation.org/job/ignition_rendering-ci-pr_any-homebrew-amd64/2758/testReport/(root)/CameraTest/ShaderSelection_2/

but at least it gives a clearer indication of the problem than before:

* https://build.osrfoundation.org/view/ign-garden/job/ignition_rendering-ci-gz-rendering7-homebrew-amd64/6/testReport/(root)/INTEGRATION_camera_ogre2_metal/test_ran/

**Comment by scpeters** [comment]
should we re-disable the test on macOS CI?

**Comment by iche033** [comment]
> should we re-disable the test on macOS CI?

+1 to disabling the test for now.

**Comment by scpeters** [comment]
> > should we re-disable the test on macOS CI?
> 
> +1 to disabling the test for now.

https://github.com/gazebosim/gz-rendering/pull/720/commits/62fd7220cddd6d2a8249b59ead2895a9694228ea

**Review by iche033 — APPROVED** [review]

**Pull request merged**
