### PR TITLE
ign-redering working on windows

### PR DESCRIPTION
**Pull request by ahcorde**
Signed-off-by: ahcorde <ahcorde@gmail.com>

# 🦟 Bug fix

## Summary

This changes allow to run ign-rendering on Windows:

I added some required files in Media, the version that we installed with conda it's 1.12 there are some thing that need to be updated.

I also update:
 - simple_demo
 - thermal_camera. This demo is partially working, there are some path that are broken due the "\" and "/". The duck is not showed.

Captura2

There are some other things that may require some more changes.

FYI @WilliamLewww @chapulina @mjcarroll @iche033 @j-rivero 

## Checklist
- [x] Signed all commits for DCO
- [ ] Added tests
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [ ] `codecheck` passed (See [contributing](https://ignitionrobotics.org/docs/all/contributing#contributing-code))
- [ ] All tests passed (See [test coverage](https://ignitionrobotics.org/docs/all/contributing#test-coverage))
- [ ] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Aignitionrobotics+repo%3Aosrf%2Fsdformat+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge**

### CODE REVIEW

**Comment by chapulina** [comment]
@ahcorde , do you have plans to go back to this PR? Edifice will EOL next week, should this be retargeted at `ign-rendering6`?

**Comment by ahcorde** [comment]
I was able to make Windows work with Ogre 1.12 I don't remember, but I think this version is not working properly in Ubuntu (we are using Ogre1.9).

Maybe we should versioned the folder `ogre/src/media/` to -> `ogre/src/media/1.9` and `ogre/src/media/1.12`.

I don't' know how does it sound, I can put some time on this if this makes sense at same point the future. 

Anyhow we should retarget this to ign-gazebo6

**Comment by chapulina** [comment]
> Maybe we should versioned the folder ogre/src/media/ to -> ogre/src/media/1.9 and ogre/src/media/1.12.

Humm I see. Officially we only support 1.9, and others can use higher minor versions at their own risk. But if this is required for Windows to work we should consider supporting that too. It's not ideal to duplicate the media though.

**Comment by azeey** [comment]
Ogre now works in windows since https://github.com/gazebosim/gz-rendering/pull/992. I'll go ahead and close this issue since we're no longer working on it.

**Pull request closed without merging**
