### PR TITLE
From - LuxCore Render Engine Example #505

### PR DESCRIPTION
**Pull request by sanjuksha**
Original PR - https://github.com/gazebosim/gz-rendering/pull/505

 # 🎉 [LuxCore](https://luxcorerender.org/) Render Engine

Peek 2022-06-02 13-25

Example renders:
<p float="left">
  
  
  
</p>

## Summary
This pull request creates an example plugin using the [LuxCore](https://luxcorerender.org/) render engine. The implementation is incomplete and only supports basic scenes. Some parameters of the engine are hardcoded and can be adjusted for different effects:

https://wiki.luxcorerender.org/LuxCore_SDL_Reference_Manual_v2.5

## How to build and run the example
Download the LuxCoreSDK using the following link (make sure to download the SDK and not the standalone): https://luxcorerender.org/download/

1. Build and install ign-rendering:
```
cd ign-rendering
mkdir build
cd build
cmake ..
make install
```
2. Build the example:
```
export LUXCORE_SDK_PATH=<PATH_TO_LUXCORE_SDK_DIRECTORY>
cd ../examples/lux_core_engine
mkdir build
cd build
cmake ..
make
```
3. Run the example:
```
export IGN_RENDERING_PLUGIN_PATH=$PWD
./simple_demo
```

## Checklist
- [ ] Signed all commits for DCO
- [ ] Added tests
- [ ] Added example and/or tutorial
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [ ] `codecheck` passed (See [contributing](https://ignitionrobotics.org/docs/all/contributing#contributing-code))
- [ ] All tests passed (See [test coverage](https://ignitionrobotics.org/docs/all/contributing#test-coverage))
- [ ] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Aignitionrobotics+repo%3Aosrf%2Fsdformat+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge**

### CODE REVIEW

**Review by ahcorde — CHANGES_REQUESTED** [review]
I made some review comments here https://github.com/gazebosim/gz-rendering/pull/505/files

Do you mind to include them ?

**Comment by iche033** [comment]
The example builds for me but when I tried to run it, I get the following error:

```
terminate called after throwing an instance of 'std::runtime_error'
  what():  No hardware device selected or available
Aborted (core dumped)
```

Did you run into this error? The demos in the luxcore SDK work for me though.

**Comment by sanjuksha** [comment]
> ### **[iche033](/iche033) ** commented [15 hours ago](#issuecomment-1258824862)

So I tried running but I didn't get that error. The only runtime error log I see is when I terminate the example manually, but I suppose that is expected ?
```
^[terminate called after throwing an instance of 'std::runtime_error'
  what():  CUDA driver API error cuGetErrorName(ERROR) (code: 4, file:/home/vsts/work/1/s/LinuxCompile/LuxCore-sdk/src/luxrays/devices/cudadevice.cpp, line: 418): cuGetErrorString(ERROR)

Aborted (core dumped)
```

**Comment by sanjuksha** [comment]
Results after running simple demo

image

**Comment by iche033** [comment]
what graphics card to you have? Can you post the output of `nvidia-smi`?

**Comment by sanjuksha** [comment]
> 

image

**Comment by iche033** [comment]
I made some changes in [b723c06](https://github.com/gazebosim/gz-rendering/pull/727/commits/b723c0615951ebfbcd11bf9043e3f7ec6beefd9f) to let user configure the render engine type to use. The problem I ran into before was that I think I just didn't have updated drives for OCL to work. The user can now choose other rendering engine type by specifying it as a command line arg, e.g. `./simple_demo RTPATHCPU`. I also updated `README.md` with new instructions.

**Comment by iche033** [comment]
Thanks for adding the doxygen comments. I went through the code and did a few more doc and style changes to be consistent with Gazebo's coding style, [bb43b40](https://github.com/gazebosim/gz-rendering/pull/727/commits/bb43b40252fe43d2eab110c90f87e425d56fdd76):

* removed white spaces
* added new line between functions
* wrapped line to max 80 chars
* added space between `//` and text comment
* added `override` to more functions and changed their doc comment to `Documentation inherited`
* declare each variable in a new line.
* renamed demo executable to `luxcore_demo`

@sanjuksha can you take a quick look at the changes. If everything looks good, we can get this merged.

**Comment by sanjuksha** [comment]
Sure, taking a look now.

**Comment by sanjuksha** [comment]
> I made some review comments here https://github.com/gazebosim/gz-rendering/pull/505/files
> 
> Do you mind to include them ?

Added all the changes based on those comments in this PR

**Review by iche033 — APPROVED** [review]

**Pull request merged**
