### PR TITLE
Merge ign-rendering6 ➡️  main

### PR DESCRIPTION
**Pull request by chapulina**
# ➡️  Forward port

Port `ign-rendering6 ` ➡️  `main`

Branch comparision: https://github.com/ignitionrobotics/ign-rendering/compare/main...ign-rendering6

* Required by https://github.com/gazebosim/gz-sensors/pull/247

**Note to maintainers**: Remember to **Merge** with commit (not squash-merge or rebase)

### CODE REVIEW

**Review by ahcorde — CHANGES_REQUESTED** [review]
there are two new windows warnings  https://build.osrfoundation.org/job/ign_rendering-pr-win/2734/

**Review by ahcorde — CHANGES_REQUESTED** [review]
is this test `INTEGRATION_wide_angle_camera` flaky on macOS ?

**Comment by chapulina** [comment]
> is this test INTEGRATION_wide_angle_camera flaky on macOS ?

Just barely?

https://build.osrfoundation.org/job/ignition_rendering-ci-main-homebrew-amd64/107/testReport/(root)/WideAngleCamera_WideAngleCameraTest/WideAngleCamera_ogre/history/

I retriggered CI, let's see

**Comment by iche033** [comment]
hmm there are quite a bit of changes to the test framework in https://github.com/gazebosim/gz-rendering/pull/685 that will create conflicts with the forward port here. Maybe we should wait till the ogre 2.3 PR gets in first then resolve conflicts and get this forward port in. We'll need to check and verify that bounding box still works.

**Comment by mjcarroll** [comment]
This is first on my list in the morning to look at.

**Comment by mjcarroll** [comment]
Still failing from the forward port:

GpuRaysTest.Visibility - From #625, didn't port forward cleanly because compositor workspace changed, I have pinged @darksylinc for a quick fix here

The following three are all ogreroot destructor related issues, I can reproduce them locally, but not sure what has changed to make them happen: 

INTEGRATION_camera_ogre_gl3plus.test_ran
INTEGRATION_thermal_camera_ogre_gl3plus.test_ran
INTEGRATION_wide_angle_camera_ogre_gl3plus.test_ran

**Comment by mjcarroll** [comment]
> The following three are all ogreroot destructor related issues, I can reproduce them locally, but not sure what has changed to make them happen

I'm not sure why, but backing out a section of logic from #617 removes this segfault with no other adverse affects that I can see locally for both clang and gcc.  This patch fixes it: https://github.com/gazebosim/gz-rendering/pull/679/commits/44f1a1a8bce9d0aa56decae64b79997efb67be82

@iche033 Do you see any reason to not do this?

**Comment by darksylinc** [comment]
> The following three are all ogreroot destructor related issues, I can reproduce them locally, but not sure what has changed to make them happen:

Can you post the callstack? (when it crashes).

I suspect that bug is related to #617 (see #615 for explanation).

That PR fixed leaks. However proper shutdown can be tricky to get because the following is an example of a bug:

```cpp
{
MeshPtr myMesh = ...;
MaterialPtr myMaterial = ...;
   {
       Ogre::Root::shutdown();
   }

// CRASH! myMesh & myMaterial destructors will be called however Ogre has already been shutdown
}
```

Basically smart ptrs need to be reset before Ogre gets shutdown (either by moving Ogre shutdown later, or force-resetting the smart ptrs by hand earlier, or destroying the classes that contain theses smart ptrs before shutdown).
A leaked smart ptr on the Gazebo side can easily explain this.

I suspect this is what's happening.

**Comment by mjcarroll** [comment]
> Can you post the callstack? (when it crashes).

All three fail in the same location, here is the callstack for INTEGRATION_camera: https://gist.github.com/mjcarroll/321a7122ad6d4f3a7087db56b20d0fe8

**Comment by darksylinc** [comment]
OH the crash is in Ogre 1.9, hmmm.

**Comment by darksylinc** [comment]
I'm looking into this. Your fix introduces leaks; which is why it stops crashing (it will no longer crash at a dangling pointer, because the pointer is still alive... because it's leaking).

gz-rendering is leaking other handles. I'll post the patch here

**Comment by darksylinc** [comment]
@mjcarroll the following patch undoes your change and fixes an gazebo/ogre bug (who's really at fault is debatable):

```diff
diff --git a/ogre/src/OgreThermalCamera.cc b/ogre/src/OgreThermalCamera.cc
index 8c090ffc..5975c805 100644
--- a/ogre/src/OgreThermalCamera.cc
+++ b/ogre/src/OgreThermalCamera.cc
@@ -297,6 +297,16 @@ void OgreThermalCamera::Destroy()
   if (!this->ogreCamera || !this->scene->IsInitialized())
     return;
 
+  if (this->dataPtr->thermalInstance)
+  {
+    // Do not leave a reference to this->dataPtr->thermalMaterial
+    Ogre::MaterialPtr nullMaterial;
+    this->dataPtr->thermalInstance->getTechnique()
+      ->getOutputTargetPass()
+      ->getPass(0)
+      ->setMaterial(nullMaterial);
+  }
+
   // remove thermal textures
   if (this->dataPtr->ogreThermalTexture)
   {
@@ -312,6 +322,13 @@ void OgreThermalCamera::Destroy()
     this->dataPtr->ogreHeatSourceTexture = nullptr;
   }
 
+  if (!this->dataPtr->thermalMaterial.isNull())
+  {
+    Ogre::MaterialManager::getSingleton().remove(
+        this->dataPtr->thermalMaterial->getHandle());
+    this->dataPtr->thermalMaterial.setNull();
+  }
+
   Ogre::SceneManager *ogreSceneManager;
   ogreSceneManager = this->scene->OgreSceneManager();
   if (ogreSceneManager == nullptr)
diff --git a/src/base/BaseScene.cc b/src/base/BaseScene.cc
index ff97f951..57d1d047 100644
--- a/src/base/BaseScene.cc
+++ b/src/base/BaseScene.cc
@@ -1416,8 +1416,6 @@ bool BaseScene::LegacyAutoGpuFlush() const
 //////////////////////////////////////////////////
 void BaseScene::Clear()
 {
-  this->nodes->DestroyAll();
-  /*
   this->DestroyNodes();
   auto root = this->RootVisual();
   if (root)
@@ -1425,7 +1423,6 @@ void BaseScene::Clear()
     root->RemoveChildren();
     this->DestroyNode(root);
   }
-  */
   this->DestroyMaterials();
   this->nextObjectId = gz::math::MAX_UI16;
 }
```

This fixes the crashes for:

 - INTEGRATION_camera_ogre_gl3plus.test_ran
 - INTEGRATION_thermal_camera_ogre_gl3plus.test_ran

However now this sample:

 - INTEGRATION_wide_angle_camera_ogre_gl3plus.test_ran

Crashes at a different place because `OgreWideAngleCamera::Destroy` gets called twice.

The fix is to either see why is Destroy() getting called twice (@iche033 will know better) or place a nullptr check:

```cpp
for (unsigned int i = 0u; i < this->dataPtr->kEnvCameraCount; ++i)
{
  if (this->dataPtr->envRenderTargets[i]) // CHECK!!!
  {
    OgreRTShaderSystem::DetachViewport(this->dataPtr->envViewports[i],
                                       this->scene);
    
    this->dataPtr->envRenderTargets[i]->removeAllViewports();
    this->dataPtr->envRenderTargets[i] = nullptr;
  }

  if (this->dataPtr->envCameras[i]) // CHECK!!!
  {
    this->scene->OgreSceneManager()->destroyCamera(
        this->dataPtr->envCameras[i]->getName());
    this->dataPtr->envCameras[i] = nullptr;
  }
}
```

The first time's callstack is this one:

```
1  gz::rendering::v7::OgreWideAngleCamera::Destroy                                                        OgreWideAngleCamera.cc 147  0x7ffff58bc43e 
2  gz::rendering::v7::BaseStore<gz::rendering::v7::Sensor, gz::rendering::v7::OgreSensor>::DestroyImpl    BaseStorage.hh         956  0x7ffff584724e 
3  gz::rendering::v7::BaseStore<gz::rendering::v7::Sensor, gz::rendering::v7::OgreSensor>::DestroyByIndex BaseStorage.hh         723  0x7ffff5846142 
4  gz::rendering::v7::BaseStore<gz::rendering::v7::Sensor, gz::rendering::v7::OgreSensor>::DestroyAll     BaseStorage.hh         734  0x7ffff58461ac 
5  gz::rendering::v7::BaseStoreWrapper<gz::rendering::v7::Node, gz::rendering::v7::Sensor>::DestroyAll    BaseStorage.hh         1460 0x7ffff7f9d114 
6  gz::rendering::v7::BaseCompositeStore<gz::rendering::v7::Node>::DestroyAll                             BaseStorage.hh         1216 0x7ffff7f9f03f 
7  gz::rendering::v7::BaseScene::DestroyNodes                                                             BaseScene.cc           333  0x7ffff7f8a5c6 
8  gz::rendering::v7::BaseScene::Clear                                                                    BaseScene.cc           1419 0x7ffff7f932b1 
9  gz::rendering::v7::OgreScene::Clear                                                                    OgreScene.cc           294  0x7ffff5894c02 
10 gz::rendering::v7::BaseScene::Destroy                                                                  BaseScene.cc           1434 0x7ffff7f93451 
11 gz::rendering::v7::OgreScene::Destroy                                                                  OgreScene.cc           300  0x7ffff5894c32 
12 gz::rendering::v7::BaseStore<gz::rendering::v7::Scene, gz::rendering::v7::OgreScene>::DestroyImpl      BaseStorage.hh         956  0x7ffff584cc29 
13 gz::rendering::v7::BaseStore<gz::rendering::v7::Scene, gz::rendering::v7::OgreScene>::Destroy          BaseStorage.hh         699  0x7ffff584b9ff 
14 gz::rendering::v7::BaseRenderEngine::DestroyScene                                                      BaseRenderEngine.cc    163  0x7ffff7f87caf 
15 WideAngleCameraTest_WideAngleCamera_Test::TestBody                                                     wide_angle_camera.cc   200  0x55555557f24a 
16 testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>                         gtest.cc               2599 0x5555555cfa26 
17 testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>                            gtest.cc               2635 0x5555555c8159 
18 testing::Test::Run                                                                                     gtest.cc               2674 0x5555555a4064 
19 testing::TestInfo::Run                                                                                 gtest.cc               2853 0x5555555a4aeb 
20 testing::TestSuite::Run                                                                                gtest.cc               3012 0x5555555a5421 
21 testing::internal::UnitTestImpl::RunAllTests                                                           gtest.cc               5870 0x5555555b50db 
22 testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>       gtest.cc               2599 0x5555555d0ae7 
23 testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>          gtest.cc               2635 0x5555555c93e5 
24 testing::UnitTest::Run                                                                                 gtest.cc               5444 0x5555555b36fa 
25 RUN_ALL_TESTS                                                                                          gtest.h                2293 0x5555555e2e08 
26 main                                                                                                   gtest_main.cc          51   0x5555555e2d8a 
```

The second time is this one:

```
1  gz::rendering::v7::OgreWideAngleCamera::Destroy                                                        OgreWideAngleCamera.cc 147  0x7ffff58bc43e 
2  gz::rendering::v7::OgreWideAngleCamera::~OgreWideAngleCamera                                           OgreWideAngleCamera.cc 114  0x7ffff58bbf8d 
3  gz::rendering::v7::OgreWideAngleCamera::~OgreWideAngleCamera                                           OgreWideAngleCamera.cc 115  0x7ffff58bc122 
4  std::_Sp_counted_ptr<gz::rendering::v7::OgreWideAngleCamera *, (__gnu_cxx::_Lock_policy)2>::_M_dispose shared_ptr_base.h      377  0x7ffff58a57ec 
5  std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release                                          shared_ptr_base.h      155  0x5555555877d0 
6  std::__shared_count<(__gnu_cxx::_Lock_policy)2>::~__shared_count                                       shared_ptr_base.h      730  0x55555558622b 
7  std::__shared_ptr<gz::rendering::v7::WideAngleCamera, (__gnu_cxx::_Lock_policy)2>::~__shared_ptr       shared_ptr_base.h      1169 0x555555585eb4 
8  std::shared_ptr<gz::rendering::v7::WideAngleCamera>::~shared_ptr                                       shared_ptr.h           103  0x555555585ed4 
9  WideAngleCameraTest_WideAngleCamera_Test::TestBody                                                     wide_angle_camera.cc   200  0x55555557f32d 
10 testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>                         gtest.cc               2599 0x5555555cfa26 
11 testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>                            gtest.cc               2635 0x5555555c8159 
12 testing::Test::Run                                                                                     gtest.cc               2674 0x5555555a4064 
13 testing::TestInfo::Run                                                                                 gtest.cc               2853 0x5555555a4aeb 
14 testing::TestSuite::Run                                                                                gtest.cc               3012 0x5555555a5421 
15 testing::internal::UnitTestImpl::RunAllTests                                                           gtest.cc               5870 0x5555555b50db 
16 testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>       gtest.cc               2599 0x5555555d0ae7 
17 testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>          gtest.cc               2635 0x5555555c93e5 
18 testing::UnitTest::Run                                                                                 gtest.cc               5444 0x5555555b36fa 
19 RUN_ALL_TESTS                                                                                          gtest.h                2293 0x5555555e2e08 
20 main                                                                                                   gtest_main.cc          51   0x5555555e2d8a 
```

**Comment by darksylinc** [comment]
Ahhh. I realized why it gets called twice. It's the same problem as Ogre:

```
TEST_F(WideAngleCameraTest, WideAngleCamera)
{
  auto camera = scene->CreateWideAngleCamera("WideAngleCamera");

  ...  

  // Clean up
  engine->DestroyScene(scene);

   //Crash! camera destructor is called here!
}
```

**Comment by darksylinc** [comment]
OK this is the latest patch:

```diff
diff --git a/ogre/src/OgreThermalCamera.cc b/ogre/src/OgreThermalCamera.cc
index 8c090ffc..5975c805 100644
--- a/ogre/src/OgreThermalCamera.cc
+++ b/ogre/src/OgreThermalCamera.cc
@@ -297,6 +297,16 @@ void OgreThermalCamera::Destroy()
   if (!this->ogreCamera || !this->scene->IsInitialized())
     return;
 
+  if (this->dataPtr->thermalInstance)
+  {
+    // Do not leave a reference to this->dataPtr->thermalMaterial
+    Ogre::MaterialPtr nullMaterial;
+    this->dataPtr->thermalInstance->getTechnique()
+      ->getOutputTargetPass()
+      ->getPass(0)
+      ->setMaterial(nullMaterial);
+  }
+
   // remove thermal textures
   if (this->dataPtr->ogreThermalTexture)
   {
@@ -312,6 +322,13 @@ void OgreThermalCamera::Destroy()
     this->dataPtr->ogreHeatSourceTexture = nullptr;
   }
 
+  if (!this->dataPtr->thermalMaterial.isNull())
+  {
+    Ogre::MaterialManager::getSingleton().remove(
+        this->dataPtr->thermalMaterial->getHandle());
+    this->dataPtr->thermalMaterial.setNull();
+  }
+
   Ogre::SceneManager *ogreSceneManager;
   ogreSceneManager = this->scene->OgreSceneManager();
   if (ogreSceneManager == nullptr)
diff --git a/ogre/src/OgreWideAngleCamera.cc b/ogre/src/OgreWideAngleCamera.cc
index 28590a37..dfc6bb77 100644
--- a/ogre/src/OgreWideAngleCamera.cc
+++ b/ogre/src/OgreWideAngleCamera.cc
@@ -158,15 +158,21 @@ void OgreWideAngleCamera::Destroy()
 
   for (unsigned int i = 0u; i < this->dataPtr->kEnvCameraCount; ++i)
   {
-    OgreRTShaderSystem::DetachViewport(this->dataPtr->envViewports[i],
-        this->scene);
+    if (this->dataPtr->envRenderTargets[i])
+    {
+      OgreRTShaderSystem::DetachViewport(this->dataPtr->envViewports[i],
+                                         this->scene);
 
-    this->dataPtr->envRenderTargets[i]->removeAllViewports();
-    this->dataPtr->envRenderTargets[i] = nullptr;
+      this->dataPtr->envRenderTargets[i]->removeAllViewports();
+      this->dataPtr->envRenderTargets[i] = nullptr;
+    }
 
-    this->scene->OgreSceneManager()->destroyCamera(
-        this->dataPtr->envCameras[i]->getName());
-    this->dataPtr->envCameras[i] = nullptr;
+    if (this->dataPtr->envCameras[i])
+    {
+      this->scene->OgreSceneManager()->destroyCamera(
+          this->dataPtr->envCameras[i]->getName());
+      this->dataPtr->envCameras[i] = nullptr;
+    }
   }
 
   if (this->dataPtr->envCubeMapTexture)
diff --git a/src/base/BaseScene.cc b/src/base/BaseScene.cc
index ff97f951..57d1d047 100644
--- a/src/base/BaseScene.cc
+++ b/src/base/BaseScene.cc
@@ -1416,8 +1416,6 @@ bool BaseScene::LegacyAutoGpuFlush() const
 //////////////////////////////////////////////////
 void BaseScene::Clear()
 {
-  this->nodes->DestroyAll();
-  /*
   this->DestroyNodes();
   auto root = this->RootVisual();
   if (root)
@@ -1425,7 +1423,6 @@ void BaseScene::Clear()
     root->RemoveChildren();
     this->DestroyNode(root);
   }
-  */
   this->DestroyMaterials();
   this->nextObjectId = gz::math::MAX_UI16;
 }
diff --git a/test/integration/wide_angle_camera.cc b/test/integration/wide_angle_camera.cc
index a78a8b89..bfe23778 100644
--- a/test/integration/wide_angle_camera.cc
+++ b/test/integration/wide_angle_camera.cc
@@ -315,4 +315,6 @@ TEST_F(WideAngleCameraTest, Projection)
 
   // Clean up
   engine->DestroyScene(scene);
+
+  ASSERT_EQ(1u, camera.use_count());
 }
```

**Review by scpeters — APPROVED** [review]

**Comment by iche033** [comment]
thanks for the fixing crash. Sometimes the `Destroy` function is called when a node is removed manually and sometimes it gets called on destructor, and other times they are called in both cases so I always make sure they the `Destroy` function is safe to be called multiple times. The patch looks good.

**Comment by mjcarroll** [comment]
Yes, thanks @darksylinc!  I think we are in pretty good shape here.

**Review by iche033 — APPROVED** [review]
looks good to me. Bounding box camera works for me on Focal

**Review by mjcarroll — APPROVED** [review]
I approve of the things I didn't do.

**Pull request merged**
